SELECT * FROM Professor
SELECT * FROM Email 


INSERT INTO Professor ( --INSERINDO DADOS NA TABELA ALUNO
	RA,
	Nome
)
Values(
	1245678910,
	'Nova aula adicionada'
) --PARA SABER QUE  A TRIGGER FOI DISPARADA IRÁ APARECER (1 ROW(S) AFFECTED)